# Generated by Django 5.0.6 on 2025-11-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="todo_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
